server:
  port: 8083

spring:
  application:
    name: events-service
  datasource:
    url: jdbc:mysql://localhost:3306/events_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092