server:
  port: 8082

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:h2:mem:broko-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: broko
    password: secret123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

broko:
  jwt:
    secret: super-secret-jwt-key
    expiration: 3600000