server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver